basicConstraints = CA:FALSE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
subjectAltName = DNS:wazuh.indexer, DNS:node-1, DNS:localhost, IP:172.20.0.11, IP:127.0.0.1