[ req ]
default_bits        = 2048
default_md          = sha256
distinguished_name  = dn
string_mask        = utf8only
x509_extensions    = v3_root

[ dn ]
0.domainComponent           = DC
domainComponent            = Wazuh
organizationalUnitName      = Wazuh
organizationName           = Wazuh
stateOrProvinceName        = California
countryName               = US
commonName                = Wazuh Root CA

[ v3_root ]
basicConstraints = critical, CA:true, pathlen:0
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid
keyUsage = critical, keyCertSign, cRLSign, digitalSignature