cluster.name: wazuh-cluster
node.name: node-1
node.master: true
node.data: true

path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

network.host: 0.0.0.0
http.port: 9200

discovery.type: single-node

plugins.security.ssl.transport.pemcert_filepath: certs/node-1.pem
plugins.security.ssl.transport.pemkey_filepath: certs/node-1-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: certs/node-1.pem
plugins.security.ssl.http.pemkey_filepath: certs/node-1-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: certs/root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false
plugins.security.authcz.admin_dn:
  - CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US
plugins.security.nodes_dn:
  - CN=*
action.auto_create_index: "true"
bootstrap.memory_lock: true
